name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker image with incremental tag
        run: |
          IMAGE_NAME="vishalkumar02976/my-site"
          VERSION_TAG="v${{ github.run_number }}"

          echo "Building image with tag $IMAGE_NAME:$VERSION_TAG"
          docker build . -t $IMAGE_NAME:$VERSION_TAG
          docker push $IMAGE_NAME:$VERSION_TAG

      - name: Push 'latest' only on manual trigger
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          IMAGE_NAME="vishalkumar02976/my-site"
          VERSION_TAG="v${{ github.run_number }}"

          echo "Tagging and pushing $IMAGE_NAME:latest"
          docker tag $IMAGE_NAME:$VERSION_TAG $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
